require 'models/contact'
require 'models/location'
require 'models/surface'
require 'models/posting_order'
require 'models/location_type'
require 'models/surface_type'
require 'models/poster_worker'
require 'active_support/inflector'