# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b45aa7b5eb17a523a7678a012c581e21ac8d643d1b7fec4bbfcc2e0a71a37ccf57e60e9fc86afb54f6169683b346f43b294b4eab372bae4db6c038b206dad01d

test:
  secret_key_base: 48252489f94b73a074d1d8373c490a67a0197b038308dbd6eb04fdadd1ca770362ed16c8ec046e554f00c4290631753bd4a2595aa8bbb80ec925b5202e203311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
